
/**
 * CreativeWork interface 
 * @see {@link https://schema.org/CreativeWork}
 */
import AggregateRating from "./AgregateRating";
import AlignmentObject from "./AlignmentObject";
import Audience from "./Audience";
import AudioObject from "./AudioObject";
import Claim from "./Claim";
import Clip from "./Clip";
import CorrectionComment from "./CorrectionComment";
import Country from "./Country";
import DefinedTerm from "./DefinedTerm";
import Demand from "./Demand";
import Grant from "./Grant";
import ImageObject from "./ImageObject";
import InteractionCounter from "./InteractionCounter";
import ItemList from "./ItemList";
import MediaObject from "./MediaObject";
import MusicRecording from "./MusicRecording";
import Offer from "./Offer";
import Organization from "./Organization";
import Person from "./Person";
import Place from "./Place";
import Product from "./Product";
import PublicationEvent from "./PublicationEvent";
import QuantitativeValue from "./QuantitativeValue";
import Rating from "./Rating";
import Review from "./Review";
import SizeSpecification from "./SizeSpecification";
import Thing from "./Thing";
import VideoObject from "./VideoObject";
import WebPage from "./Webpage";


export default interface CreativeWork {
  about?: Thing;
  abstract?: string;
  accessMode?: string;
  accessModeSufficient?: ItemList;
  accessibilityAPI?: string;
  accessibilityControl?: string;
  accessibilityFeature?: string;
  accessibilityHazard?: string;
  accessibilitySummary?: string;
  accountablePerson?: Person;
  acquireLicensePage?: CreativeWork | URL | string;
  aggregateRating?: AggregateRating;
  alternativeHeadline?: string;
  archivedAt?: URL | WebPage | string;
  assesses?: DefinedTerm | string;
  associatedMedia?: MediaObject;
  audience?: Audience;
  audio?: AudioObject | Clip | MusicRecording;
  author?: Organization | Person;
  award?: string;
  character?: Person;
  citation?: CreativeWork | string;
  comment?: Comment;
  commentCount?: number;
  conditionsOfAccess?: string;
  contentLocation?: Place;
  contentRating?: Rating | string;
  contentReferenceTime?: string;
  contributor?: Organization | Person;
  copyrightHolder?: Organization | Person;
  copyrightNotice?: string;
  copyrightYear?: number;
  correction?: CorrectionComment | string | URL;
  countryOfOrigin?: Country;
  creativeWorkStatus?: DefinedTerm | string;
  creator?: Organization | Person;
  creditText?: string;
  dateCreated?: string;
  dateModified?: string;
  datePublished?: string;
  discussionUrl?: URL | string;
  editEIDR?: string | URL;
  editor?: Person;
  educationalAlignment?: AlignmentObject;
  educationalLevel?: DefinedTerm | string | URL;
  educationalUse?: DefinedTerm | string;
  encoding?: MediaObject;
  encodingFormat?: string | URL;
  exampleOfWork?: CreativeWork;
  expires?: string;
  funder?: Organization | Person;
  funding?: Grant;
  genre?: string | URL;
  hasPart?: CreativeWork;
  headline?: string;
  inLanguage?: string;
  interactionStatistic?: InteractionCounter;
  interactivityType?: string;
  interpretedAsClaim?: Claim;
  isAccessibleForFree?: boolean;
  isBasedOn?: CreativeWork | Product | URL | string;
  isFamilyFriendly?: boolean;
  isPartOf?: CreativeWork | URL | string;
  keywords?: DefinedTerm | string | URL;
  learningResourceType?: DefinedTerm | string;
  license?: CreativeWork | URL | string;
  locationCreated?: Place;
  mainEntity?: Thing;
  maintainer?: Organization | Person;
  material?: Product | string | URL;
  materialExtent?: QuantitativeValue | string;
  mentions?: Thing;
  offers?: Demand | Offer;
  pattern?: DefinedTerm | string;
  position?: number | string;
  producer?: Organization | Person;
  provider?: Organization | Person;
  publication?: PublicationEvent;
  publisher?: Organization | Person;
  publisherImprint?: Organization;
  publishingPrinciples?: CreativeWork | URL | string;
  recordedAt?: Event;
  releasedEvent?: PublicationEvent;
  review?: Review;
  schemaVersion?: string | URL;
  sdDatePublished?: string;
  sdLicense?: CreativeWork | URL | string;
  sdPublisher?: Organization | Person;
  size?: DefinedTerm | QuantitativeValue | SizeSpecification | string;
  sourceOrganization?: Organization;
  spatial?: Place;
  spatialCoverage?: Place;
  sponsor?: Organization | Person;
  teaches?: DefinedTerm | string;
  temporal?: string;
  temporalCoverage?: string | URL;
  string?: string;
  thumbnail?: ImageObject;
  thumbnailUrl?: URL | string;
  timeRequired?: string;
  translationOfWork?: CreativeWork;
  translator?: Organization | Person;
  typicalAgeRange?: string;
  usageInfo?: CreativeWork | URL;
  version?: number | string;
  video?: Clip | VideoObject;
  workExample?: CreativeWork;
  workTranslation?: CreativeWork;
}